add k8s node_ip for metaflow
metaflowys/metaflow pull request #143
Opened 2022-07-01 02:58 UTC by StrayLittlePunk

**Phenomenon and reproduction steps**

**Root cause and solution**

add k8s node_ip for metaflow to communicate with metaflow-server

**Impactions**

**Test method**

**Affected branch(es)**

* main

**Checklist**

- [ ] Dependencies update required
- [ ] Common bug (similar problem in other repo)

2022-07-01 03:07 UTC, sharang commented on agent/src/trident.rs
> +        if let Some(ip) = get_k8s_node_ip() {
要写注释

2022-07-01 03:07 UTC, sharang commented on agent/src/utils/environment.rs
> +pub fn get_k8s_node_ip() -> Option<IpAddr> {
get_k8s_local_node_ip

2022-07-01 03:08 UTC, sharang commented on agent/src/utils/environment.rs
> +            Err(e) => warn!("get K8S_NODE_IP_FOR_METAFLOW environment var failed: {}", e),
这个环境变量并不一定存在，因此只是成功时打印一下INFO即可，失败不用打印日志

2022-07-01 03:08 UTC, sharang commented on agent/src/trident.rs
> +        if let Some(ip) = get_k8s_node_ip() {
且也要打印日志，说ctrl-ip从xx切换为k8s node ip xx了。info

2022-07-01 03:08 UTC, sharang commented on agent/src/trident.rs
> +        if let Some(ip) = get_k8s_node_ip() {
这里逻辑不对，ctrl-mac没有刷新。

2022-07-01 03:09 UTC, sharang commented on agent/src/trident.rs
> +        if let Some(ip) = get_k8s_node_ip() {
应该是：

```
if 有node ip
    get_route_src_ip_and_mac(node_ip)
else
    get_route_src_ip_and_mac(controller-ips[0])
```

2022-07-01 03:10 UTC, sharang commented on agent/src/config/handler.rs
> +            ctrl_ip = ip;
这里最好也反过来，避免查一次路由

2022-07-01 03:11 UTC, StrayLittlePunk commented on agent/src/utils/environment.rs
> +            Err(e) => warn!("get K8S_NODE_IP_FOR_METAFLOW environment var failed: {}", e),
不一定存在没有打日志，VarError::NoPresent 表示不存在，这个情况没做判断，所以打印的都是解析失败的日志

2022-07-01 03:13 UTC, StrayLittlePunk commented on agent/src/config/handler.rs
> +            ctrl_ip = ip;
总是要查，得到ctrl_mac要查一次路由

2022-07-01 03:18 UTC, rvql requested changes

2022-07-01 03:18 UTC, rvql commented on agent/src/utils/environment.rs
> +            Err(e) => warn!("get K8S_NODE_IP_FOR_METAFLOW environment var failed: {}", e),
这个错误提示不对

2022-07-01 03:18 UTC, rvql commented on agent/src/common/consts.rs
> +pub const K8S_NODE_IP_FOR_METAFLOW: &str = "K8S_NODE_IP_FOR_METAFLOW";
这个可以直接放`environment.rs`里

2022-07-01 05:52 UTC, sharang commented on agent/src/config/handler.rs
> +        info!("ctrl_ip {}", ctrl_ip);
ctrl_ip is {}

2022-07-01 05:52 UTC, sharang commented on agent/src/trident.rs
> +                    "use K8S_NODE_IP_FOR_METAFLOW env ip as destination_ip({})",
as ctrl_ip {}

2022-07-01 05:54 UTC, sharang commented on agent/src/utils/environment.rs
> +                warn!("get K8S_NODE_IP_FOR_METAFLOW environment var failed: {}", e);
这里不需要有warn吧，因为有没有此env的场景

2022-07-01 06:09 UTC, StrayLittlePunk commented on agent/src/utils/environment.rs
> +                warn!("get K8S_NODE_IP_FOR_METAFLOW environment var failed: {}", e);
VarError::NoPresent 表示不存在，这个情况没做判断，所以打印的都是解析失败的日志

2022-07-01 06:43 UTC, sharang commented on agent/src/config/handler.rs
> +        // Use environment variables node ip to determine the ID reported by the metaflow-agent
Use environment variables K8S_NODE_IP_FOR_METAFLOW to determine the ctrl reported by metaflow-agent

2022-07-01 06:44 UTC, sharang commented on agent/src/config/handler.rs
> +        // Use environment variables node ip to determine the ID reported by the metaflow-agent
稍微改改

2022-07-01 06:45 UTC, sharang commented on agent/src/config/handler.rs
> +        // Use environment variables node ip to determine the ID reported by the metaflow-agent
Use env.K8S_NODE_IP_FOR_METAFLOW as the ctrl_ip reported by metaflow-agent if available

2022-07-01 07:04 UTC, sharang submitted a review, later dismissed

2022-07-01 07:08 UTC, rvql requested changes

2022-07-01 07:08 UTC, rvql commented on agent/src/trident.rs
> +                get_route_src_ip_and_mac(&ip).context("failed getting control ip and mac")?
这里应该直接用ip在本地接口列表找mac，而不是查route

2022-07-01 08:03 UTC, rvql requested changes

2022-07-01 08:03 UTC, rvql commented on agent/src/trident.rs
> +                    .unwrap();
如果没有呢？考虑问题要周全

2022-07-01 08:19 UTC, StrayLittlePunk commented on agent/src/trident.rs
> +                    .unwrap();
按照你的说法，那没有又往哪里找

2022-07-01 11:58 UTC, sharang commented on agent/src/trident.rs
> +                get_route_src_ip_and_mac(&ip).context("failed getting control ip and mac")?
嗯，这样更准确

2022-07-01 11:59 UTC, sharang commented on agent/src/trident.rs
> +                    .unwrap();
这里应该写个函数吧？ @StrayLittlePunk

2022-07-01 12:00 UTC, sharang commented on agent/src/trident.rs
> +                    .unwrap();
没找到就要报错打日志了

2022-07-01 12:01 UTC, sharang commented on agent/src/trident.rs
> +                    .unwrap();
在 get_route_src_ip_and_mac 的附近写一个 lookup_local_interface_mac_by_ip 之类的函数？
或者 lookup_local_interface_by_ip 之类的，从结果中获取mac。

2022-07-02 03:51 UTC, sharang commented on agent/src/trident.rs
> +                    .unwrap();
@StrayLittlePunk 将这段逻辑放到一个函数中吧

2022-07-04 03:25 UTC, sharang approved these changes

2022-07-04 03:38 UTC, merged