[Agent] Ebpf log support https
metaflowys/metaflow pull request #266
Opened 2022-07-12 09:43 UTC by yuanchaoa

**Phenomenon and reproduction steps**

**Root cause and solution**

**Impactions**

**Test method**

**Affected branch(es)**

* main

**Checklist**

- [ ] Dependencies update required
- [ ] Common bug (similar problem in other repo)

2022-07-12 12:16 UTC, sharang approved these changes

2022-07-13 06:13 UTC, sharang submitted a review, later dismissed

2022-07-13 09:48 UTC, rvql requested changes

2022-07-13 09:48 UTC, rvql commented on agent/src/common/meta_packet.rs
> +use super::flow::L7Protocol;
放L36下面

2022-07-14 01:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/metaflowys/metaflow?pullRequest=266) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/metaflowys/metaflow?pullRequest=266) before we can accept your contribution.<br/><hr/>**yuanchao** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/metaflowys/metaflow?pullRequest=266) it.</sub>

2022-07-14 03:21 UTC, rvql approved these changes

2022-07-14 03:30 UTC, merged