fix dns compress pointer parse failed
metaflowys/metaflow pull request #87
Opened 2022-06-28 12:05 UTC by lzf575

**Phenomenon and reproduction steps**

none

**Root cause and solution**

**Impactions**

none

**Test method**

none

**Affected branch(es)**

* main

**Checklist**

- [ ] Dependencies update required
- [ ] Common bug (similar problem in other repo)

2022-06-29 00:39 UTC, sharang reviewed
commit msg不完整

2022-06-29 02:16 UTC, rvql requested changes

2022-06-29 02:16 UTC, rvql commented on agent/src/flow_generator/protocol_logs/dns.rs
> +            if name_type == DNS_NAME_RESERVERD_40 || name_type == DNS_NAME_RESERVERD_80 {
改成match吧

2022-07-04 02:12 UTC, rvql approved these changes

2022-07-04 02:28 UTC, merged